Screen:
    name: 'validate_locations'
    Header:
        title: 'Validate Location'
        BoxLayout:
            orientation: 'vertical'
            Label:
                text: 'Please validate the listed cities or locations.'
            ScrollView:
                size_hint_y: 2
                ListHolder:
                    ListHolder:
                        id: validate_locations_list
            Button:
                id: validate_location
                size_hint_y: .25
                text: 'Validate'
                on_press:
                    app.validate_location_clicked()

